game/urls.py
from django.conf.urls import url

from game import views

# SET THE NAMESPACE!
app_name = 'game'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url('^start/$', views.start, name='start'),
    url('^startgame/$', views.startgame, name='startgame'),
    url('^draw/$', views.draw, name='draw'),
    url('^meld_options/$', views.meld_options, name='meld_options'),
    url('^play_meld/$', views.play_meld, name='play_meld'),
    url('^lay_off/$', views.lay_off, name='lay_off'),
    url('^discard/$', views.discard, name='discard'),
    url('^gameover/$', views.gameover, name='gameover'),
    url('^game_stats/$', views.game_stats, name='game_stats'),
    url(r'^game_details/(?P<pk>[0-9]+)/$', views.game_details, name='game_details'),

]

gin_rummy/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from login_app import views as login_views

urlpatterns = [

    path('', login_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('login_app/', include('login_app.urls')),
    path('logout/', login_views.user_logout, name='logout'),
    path('login_app/session_expired/', login_views.session_expired, name='session_expired'),
    # path('special/', login_views.special, name='special'),
    path('session_security/', include('session_security.urls')),
    path('game/', include('game.urls')),

]

login_app/urls.py
from django.conf.urls import url

from login_app import views

# SET THE NAMESPACE!
app_name = 'login_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url('^register/$', views.register, name='register'),
    url('^user_login/$', views.user_login, name='user_login'),
]

login_app/models.py
# Create your models here.
# class UserProfileModel(models.Model):
#
#
#     # Create relationship (don't inherit from User!)
#     user = models.OneToOneField(User,    on_delete=models.CASCADE)
#     # Add any additional attributes you want can be defined below
#
#
#     # Add any additional attributes you want
#     # comment = models.CharField()
#
#     def __str__(self):
#         # Built-in attribute of django.contrib.auth.models.User !
#         return self.user.username

login_app/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

login_app/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
# ,UserProfileModelForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from game.models import Token
from game.views import reset_token
from login_app.forms import UserForm


# Create your views here.

def home(request):
    return render(request, 'login_app/home.html')


@login_required
def user_logout(request):

    reset_token(request)
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('home'))


def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']

            try:
                validate_password(password, username)

                # Save User Form to Database
                user = user_form.save()
                # Hash the password
                user.set_password(user.password)
                # Update with Hashed password
                user.save()

                # Registration Successful!
                registered = True
            except ValidationError as e:
                user_form.add_error('password', e)  # to be displayed with the field's errors
                return HttpResponse("Improper password - should be of min length 8; should not be similar to user name;  should be alpha-numeric.")

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    context = {'user_form': user_form, 'registered': registered}
    return render(request, 'login_app/registration.html', context)




def user_login(request):

    if request.method == 'POST':
        # Get : username and password
        username = request.POST.get('username')
        password = request.POST.get('password')

        # built-in auth function:
        user = authenticate(username=username, password=password)

        # If user is present !
        if user:
            # If the user is active
            if user.is_active:
                # Log the user in.
                login(request, user)
                # Send the user to their game page.

                return HttpResponseRedirect('/game/start')

            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login entered")

    else:
        # username or password are empty, redirect to the same page to retry.
        return render(request, 'login_app/login.html', {})


def session_expired(request):
    print(f'Session Id in the request is {request.session.items()}')
    token = Token.objects.get(pk=request.session['token_id'])
    token.lastUsed = datetime.datetime.now()

    return HttpResponseRedirect('/login_app/user_login/')

templates/login_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% include 'session_security/all.html' %}

    <!-- Latest compiled and minified CSS -->

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">


          <li><a class="navbar-brand" href="{% url 'home' %}">Gin Rummy </a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'login_app:register' %}">Register</a></li>

          {# logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a class="navbar-link" href="{% url 'game:game_stats' %}">Game Stats </a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/login_app/home.html
{% extends "login_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome!</h1>
    <!--{% if user.is_authenticated %}-->
        <!--<h2>Welcome {{ user.username }}!</h2>-->
    <!--{% else %}-->
        <h3>To get started with Gin Rummy,

            <ul>
            <li>go ahead and register yourself first.</li>
          <li>If already registered, login and continue. Have a good game!</li></ul></h3>
    <!--{% endif %}-->
  </div>
</div>

{% endblock %}

templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Index</h1>
    <!--{% if user.is_authenticated %}-->
        <!--<h2>Welcome {{ user.username }}!</h2>-->
    <!--{% else %}-->
        <!--<h2>Welcome to the Gin Rummy app, Have a good game!</h2>-->
    <!--{% endif %}-->
  </div>
</div>

{% endblock %}

templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'login_app:user_login' %}">
          {% csrf_token %}
          {# "HTML" way for login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password" autocomplete="off">

          <input type="submit" name="" value="Login">

          <p></p>
          <p><b>Note:</b></p>
         <ul>
           <li><b>In case there is no one available to join the game,</b></li>
           <li><b>It waits for a pre-defined interval (20 sec), </b></li>
           <li><b>And checks again; before throwing an error</b></li>
          </ul>
        </form>


    </div>
  </div>
{% endblock %}

templates/login_app/registration.html
{% extends "login_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Registration Successful! Go ahead and login now !</h1>
      {% else %}
        <h2>Go ahead and register below !</h2>
        <!--<h3>Just fill out the form.</h3>-->

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <!--{{ profile_form.as_p }}-->
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}