game/urls.py
from django.conf.urls import url

from game import views

# SET THE NAMESPACE!
app_name = 'game'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    url('^start/$', views.start, name='start'),
    url('^startgame/$', views.startgame, name='startgame'),
    url('^draw/$', views.draw, name='draw'),
    url('^meld_options/$', views.meld_options, name='meld_options'),
    url('^play_meld/$', views.play_meld, name='play_meld'),
    url('^lay_off/$', views.lay_off, name='lay_off'),
    url('^discard/$', views.discard, name='discard'),
    url('^gameover/$', views.gameover, name='gameover'),
    url('^game_stats/$', views.game_stats, name='game_stats'),
    url(r'^game_details/(?P<pk>[0-9]+)/$', views.game_details, name='game_details'),

]

gin_rummy/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

from login_app import views as login_views

urlpatterns = [

    path('', login_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('login_app/', include('login_app.urls')),
    path('logout/', login_views.user_logout, name='logout'),
    path('login_app/session_expired/', login_views.session_expired, name='session_expired'),
    # path('special/', login_views.special, name='special'),
    path('session_security/', include('session_security.urls')),
    path('game/', include('game.urls')),

]

game/models.py
# from login_app.models import UserProfileModel
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Model

from game.rummy_utils import identify_melds, string_to_cards, string_to_card


# Create your models here.


class Token(Model):

    id = models.AutoField(primary_key=True)
    state = models.IntegerField()
    user0 = models.TextField()
    user1 = models.TextField()


class RummyPlayer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # a hand should be no longer than 29 characters - that's 9 commas and 10 possibly two character numbers
    hand = models.CharField(max_length=29, blank=True, null=False, default='')

    def __str__(self):
        return self.user.username

    def identify_melds(self):
        return identify_melds(self.string_to_hand())

    def string_to_hand(self):
        return string_to_cards(self.hand)


class RummyGame(models.Model):

    player1 = models.ForeignKey(RummyPlayer, related_name='player1', on_delete=models.CASCADE)
    player2 = models.ForeignKey(RummyPlayer, related_name='player2', on_delete=models.CASCADE)
    winner = models.ForeignKey(RummyPlayer, related_name='winner', on_delete=models.CASCADE, null=True)
    loser = models.ForeignKey(RummyPlayer, related_name='loser', on_delete=models.CASCADE, null=True)
    turn = models.ForeignKey(RummyPlayer, related_name='turn', on_delete=models.CASCADE)
    current_card = models.CharField(max_length=2, blank=True, null=False, default='')
    # deck max_length: 51 commas + 52*2 possibly two digit integers = 51 + 104 = 155
    deck = models.CharField(max_length=155, blank=True, null=False, default='')
    # meld max_length: 20 cards, 19 commas, 6 | for 6 separate melds = 20*2 + 19 + 6 = 65
    melds = models.CharField(max_length=65, blank=True, null=False, default='')
    last_updated = models.DateTimeField(auto_now=True)  # this should automatically be reset every time .save() called

    def meld_string_to_melds(self):
        """
        store melds as string:
            each meld separated by |
            each card in a meld separated by ,
        :return:
        """
        return list(map(string_to_cards, self.melds.split('|')))

    def deck_string_to_deck(self):
        return string_to_cards(self.deck)

    def current_card_string_to_card(self):
        return string_to_card(self.current_card)

    def append_meld(self, meld):
        """
        append a meld string to current meld string
        :param meld: already in string format (not a list of Card objects)
        :return:
        """
        melds = self.melds.split('|')
        melds.append(meld)
        self.melds = '|'.join(melds)
        self.save()

    def remove_meld(self, meld):
        melds = self.melds.split('|')
        melds.remove(meld)
        self.melds = '|'.join(melds)
        self.save()


class GameLog(models.Model):

    game = models.ForeignKey(RummyGame, related_name='game', on_delete=models.CASCADE)
    turn = models.ForeignKey(RummyPlayer, related_name='player', on_delete=models.CASCADE)
    move_number = models.IntegerField()  # autoincrement?
    draw_option = models.TextField(choices=[('top_of_deck_card', 'top_of_deck_card'), ('current_card', 'current_card')])
    draw_card = models.CharField(max_length=2, blank=True, null=False, default='')
    meld_option = models.TextField(choices=[('play_meld', 'play_meld'), ('lay_off', 'lay_off'), ('continue_to_discard', 'continue_to_discard')])
    # meld_cards max_length: 12 commas + 13*2 possibly two digit integers = 12 + 26 = 38
    meld_cards = models.CharField(max_length=38, blank=True, null=False, default='')
    discard_card = models.CharField(max_length=2, blank=True, null=False, default='')


class PlayerStats(models.Model):
    game = models.ForeignKey(RummyGame, on_delete=models.CASCADE)
    winner = models.ForeignKey(RummyPlayer, related_name='game_winner', on_delete=models.CASCADE)
    loser = models.ForeignKey(RummyPlayer, related_name='game_loser', on_delete=models.CASCADE)

game/forms.py
from django import forms


class DrawForm(forms.Form):

    CHOICES = [('current_card', 'current_card'), ('top_of_deck_card', 'top_of_deck_card')]
    draw_choices = forms.ChoiceField(choices=CHOICES, label='draw_choices')


class MeldForm(forms.Form):

    CHOICES = [('play_meld', 'play_meld'), ('lay_off', 'lay_off'), ('continue_to_discard', 'continue_to_discard')]
    meld_choices = forms.ChoiceField(choices=CHOICES, label='meld_choices')


class DiscardForm(forms.Form):

    def __init__(self, list_of_cards, *args, **kwargs):
        super(DiscardForm, self).__init__(*args, **kwargs)
        CHOICES = [(c[0], c[1]) for c in list_of_cards]
        self.fields['cards'] = forms.ChoiceField(choices=CHOICES, label='card_choices')


class PlayMeldForm(forms.Form):

    def __init__(self, list_of_cards, *args, **kwargs):
        super(PlayMeldForm, self).__init__(*args, **kwargs)
        CHOICES = [(c[0], c[1]) for c in list_of_cards]
        self.fields['cards'] = forms.MultipleChoiceField(choices=CHOICES, label='card_choices')


class ChooseMeldForm(forms.Form):

    def __init__(self, list_of_melds, list_of_cards, *args, **kwargs):
        super(ChooseMeldForm, self).__init__(*args, **kwargs)
        meld_choices = [(m[0], m[1]) for m in list_of_melds]
        card_choices = [(c[0], c[1]) for c in list_of_cards]
        self.fields['melds'] = forms.ChoiceField(choices=meld_choices, label='meld_choices')
        self.fields['cards'] = forms.MultipleChoiceField(choices=card_choices, label='card_choices')

game/views.py
import datetime
import logging
import random
import time
from datetime import datetime, timezone

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Max
from django.http import HttpResponseRedirect
from django.shortcuts import render

from game.forms import DiscardForm, MeldForm, DrawForm, PlayMeldForm, ChooseMeldForm
from game.models import RummyGame, RummyPlayer, Token, GameLog, PlayerStats
from game.rummy_utils import (initialize_deck, cards_to_string, sort_cards, string_to_card, string_to_cards,
                              validate_meld)

# Create your views here.

# Get an instance of a logger
logger = logging.getLogger('gin_rummy')


@login_required
def start(request):
    """
    being used - has django classes
    :param request: 
    :return: 
    """

    sleep_time_sec = 5

    logger.info('User id of the current request is : %s', request.user.id)

    tokens_count = len(Token.objects.all())

    initializeTokens(tokens_count)

    tokens = Token.objects.all()

    for token in tokens:
        if token.state == 2:
            if token.user0 == request.user.username or token.user1 == request.user.username:
                request.session['token_id'] = token.id
                request.session['game_pk'] = token.id
                game = RummyGame.objects.get(pk=token.id)
                if (datetime.now(timezone.utc) - game.last_updated).seconds > settings.GAME_EXPIRY_SEC:

                    if game.player1 == game.turn:
                        game.loser = game.player1
                        game.winner = game.player2

                    else:
                        game.loser = game.player2
                        game.winner = game.player1
                        game.save()
                        return HttpResponseRedirect('/game/gameover/')

        continue

    for token in tokens:
        logger.info("Token id being picked is: %s and the token state is: %s ", token.id, token.state)
        request.session['token_id'] = token.id

        if token.state == 0:
            token.state = 1
            token.user0 = request.user.username
            token.save()
            time.sleep(sleep_time_sec)
            token = Token.objects.get(pk=token.id)

            if token.state == 2:
                logger.info('A valid user, with user id: %s, was found waiting, joining the game with him', token.user1)
                request.session['game_pk'] = token.id
                request.session['user0'] = request.user.username
                request.session['user1'] = token.user1
                return HttpResponseRedirect('/game/draw/')
            else:
                logger.info('No valid user found, even after waiting for %s secs; throwing an error', sleep_time_sec)

                reset_token(request)
                context = dict()
                context['sleep_time_sec'] = sleep_time_sec
                return render(request, 'game/game_error.html', context)

        elif token.state == 1:
            # logger.info('A valid user, with user id: %s, was found waiting, joining the game with him', token.user0)
            token.user1 = request.user.username
            token.state = 2
            token.save()

            request.session['game_pk'] = token.id
            request.session['user0'] = token.user0
            request.session['user1'] = request.user.username
            return HttpResponseRedirect('/game/startgame/')
        else:
            continue


def initializeTokens(tokensCount):
    if tokensCount < 50:
        logger.info('The tokens were not found, creating 50 tokens - to allow for 50 simultaneous games')
        for idx in range(50):
            token = Token(state=0)
            token.save()


@login_required
def startgame(request):
    """

    :param request:
    :return:

    Logic that creates the game objects, associates them to the same token and starts the game

    """
    deck = initialize_deck()

    player1 = RummyPlayer(user=User.objects.get(username=request.session['user0']))
    player2 = RummyPlayer(user=User.objects.get(username=request.session['user1']))

    hand1 = cards_to_string([deck.pop() for i in range(10)])
    hand2 = cards_to_string([deck.pop() for i in range(10)])
    player1.hand = hand1
    player2.hand = hand2
    player1.save()
    player2.save()

    current_card = deck.pop().card_to_string()
    # first turn should be randomized
    first_turn = random.choice([player1, player2])

    # Create a new game, only if NO existing game is found !


    game = RummyGame(id=request.session['game_pk'],
                     player1=player1,
                     player2=player2,
                     turn=first_turn,
                     deck=cards_to_string(deck))

    game.current_card = current_card
    game.save()

    # Commented to check the functionality with token
    request.session['game_pk'] = game.pk

    logger.info("Game started with the game ID: %s ", game.pk)
    return HttpResponseRedirect('/game/draw/')


@login_required
def gameover(request):
    """
    redirected here only if player has won (or i guess if we run out of cards?)
    :param request:
    :return:
    """

    reset_token(request)

    game_pk = request.session.get('game_pk')
    game = RummyGame.objects.get(pk=game_pk)

    context = default_turn_context(game, request)
    context['winner'] = game.winner
    context['loser'] = game.loser

    return render(request, 'game/gameover.html', context)


@login_required(login_url='/login_app/session_expired/')
def draw(request):
    """
    https://www.thespruce.com/rummy-card-game-rules-and-strategies-411141
    On each turn, players must follow this sequence:

        (1) Draw one card, either from the top of the draw pile or the top of the discard pile.

        (2) The player may (but does not have to) play a meld of cards (see "Melds" below) or add to another player's meld (see "Laying Off" below).

        (3) The player must discard one card, adding it (face up) to the top of the discard pile.
    :param request:
    :return:
    """

    game_pk = request.session.get('game_pk')
    game = RummyGame.objects.get(pk=game_pk)

    # if datetime.datetime.now - lastMove > 2 minutes, then end game.
    # Whoever's turn it is has delayed too long and is the loser
    if (datetime.now(timezone.utc) - game.last_updated).seconds > 120:

        if game.player1 == game.turn:
            game.loser = game.player1
            game.winner = game.player2

        else:
            game.loser = game.player2
            game.winner = game.player1
        game.save()
        return HttpResponseRedirect('/game/gameover/')

    if game.winner:
        return HttpResponseRedirect('/game/gameover/')

    if request.method == 'POST':
        form = DrawForm(request.POST)
        if form.is_valid():

            game_logs = GameLog.objects.filter(game=game, turn=game.turn)
            if game_logs:

                # get max move_number for game and turn combo for GameLog, increment by 1
                max_move = game_logs.aggregate(Max('move_number'))['move_number__max']
                game_log = GameLog(game=game, turn=game.turn, move_number=(max_move + 1))
            else:
                # first move of the game
                game_log = GameLog(game=game, turn=game.turn, move_number=1)
            game_log.save()

            choice = form.cleaned_data['draw_choices']
            handle_draw_choice(choice, game, game_log)
            return HttpResponseRedirect('/game/meld_options/')
    else:
        form = DrawForm()

    context = default_turn_context(game, request, form)

    return render(request, 'game/draw.html', context)


def handle_draw_choice(choice, game, game_log):

    rp = RummyPlayer.objects.get(id=game.turn.id)
    hand = game.turn.string_to_hand()
    deck = string_to_cards(game.deck)
    # how to get move number?
    game_log.draw_option = choice

    if choice == 'top_of_deck_card':
        # add top of deck_card to hand
        card = deck.pop()
        hand.append(card)
        rp.hand = cards_to_string(sort_cards(hand))
        rp.save()
        game.turn.hand = rp.hand
        game.deck = cards_to_string(deck)

    elif choice == 'current_card':
        # add current_card to hand
        card = string_to_card(game.current_card)
        hand.append(card)
        rp.hand = cards_to_string(sort_cards(hand))
        rp.save()
        game.turn.hand = rp.hand
        game.current_card = deck.pop().card_to_string()
        game.deck = cards_to_string(deck)

    game.save()
    game_log.draw_card = card.card_to_string()
    game_log.save()


@login_required
def meld_options(request):
    """
    (2) The player may (but does not have to) play a meld of cards (see "Melds" below) or add to another player's meld (see "Laying Off" below).
    :param request: 
    :return: 
    """
    game_pk = request.session.get('game_pk')
    game = RummyGame.objects.get(pk=game_pk)

    if request.method == 'POST':
        form = MeldForm(request.POST)
        if form.is_valid():

            choice = form.cleaned_data['meld_choices']
            game_log = GameLog.objects.filter(game=game, turn=game.turn).latest('move_number')
            game_log.meld_option = choice
            game_log.save()

            if choice == 'play_meld':
                return HttpResponseRedirect('/game/play_meld/')
            elif choice == 'lay_off':
                return HttpResponseRedirect('/game/lay_off/')
            elif choice == 'continue_to_discard':
                return HttpResponseRedirect('/game/discard/')
        else:
            logger.info('invalid form')
    else:
        form = MeldForm()

    context = default_turn_context(game, request, form)

    return render(request, 'game/meld_options.html', context)


@login_required
def discard(request):
    """
    discard card from hand, switch turns when done

templates/game/base.html
{% extends "login_app/base.html" %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h3>Played Melds: {{ played_melds }}</h3>
        <h3>Deck Card: {{ current_card }}</h3>
        <h1>Turn: {{ turn }}</h1>
        <h4>Hand: {{ hand }}</h4>
        <h3>Possible Melds: {{ possible_melds }}</h3>
    </div>
    <div class="turn_container">
        {% block turn_block %}
        {% endblock %}
    </div>

  </div>
{% endblock %}

templates/game/choose_meld.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:choose_meld' %}" method="post">
                    <h4>Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}

templates/game/discard.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block discard_form %}
            {% if discard_form %}
                <form action="{% url 'game:discard' %}" method="post">
                    <h4>Discard Options:</h4>
                    {% csrf_token %}
                    {% for choice in discard_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>


{% endblock %}

templates/game/draw.html
{% extends "game/base.html" %}
{% block turn_block %}
  <div class="turn_container">

    {% block gameplay_form %}
        {% if gameplay_form %}
            <form action="{% url 'game:draw' %}" method="post">
                <h4>Your Draw Options:</h4>
                {% csrf_token %}
                {% for choice in gameplay_form %}
                    {{ choice }}
                {% endfor %}
                <input type="submit" value="Select" />
            </form>
        {% else %}
            <meta http-equiv="refresh" content="5; URL={% url 'game:draw' %}">
        {% endif %}
    {% endblock %}

  </div>

{% endblock %}

templates/game/game.html
<<<<<<< HEAD
{% extends "login_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Hello! {{user_name }}</h1>
    <!--{% if user.is_authenticated %}-->
        <!--<h2>Welcome {{ user.username }}!</h2>-->
    <!--{% else %}-->
        <h3>To get started with Gin Rummy,
            <ul>
                <li>Go ahead and register yourself first.</li>
                <li>If already registered, login and continue. Have a good game!</li>
            </ul>
        </h3>
    <!--{% endif %}-->
  </div>
</div>

{% endblock %}

templates/game/game_details.html
{% extends "login_app/base.html" %}
{% load game_detail_tags %}
{% block body_block %}
  <div class="container">
    <table class="table">
  <thead>
    <tr>
      <th>Game #</th>
      <th>Move Number</th>
      <th>Turn</th>
      <th>Draw Option</th>
      <th>Draw Card</th>
      <th>Meld Option</th>
      <th>Meld Cards</th>
      <th>Discard Card</th>
    </tr>
  </thead>
  <tbody>
    {% for move in game_moves %}
    <tr>
      <td> {{ move.game_id }} </td>
      <td> {{ move.move_number }} </td>
      <td> {{ move.turn }} </td>
      <td> {{ move.draw_option }} </td>
      <td> {% string_to_card move.draw_card %} </td>
      <td> {{ move.meld_option }} </td>
      <td> {% string_to_cards move.meld_cards %} </td>
      <td> {% string_to_card move.discard_card %} </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
{% endblock %}

templates/game/game_error.html
{% extends "login_app/base.html" %}
{% block body_block %}
    <div class="container">
       <h2>Error : Couldn't start game</h2>
       <h2>We waited for {{sleep_time_sec}} seconds for another other player to log in, but couldn't find one</h2>
    </div>


{% endblock %}

templates/game/game_stats.html
{% extends "login_app/base.html" %}
{% block body_block %}
  <div class="container">
    <table class="table">
  <thead>
    <tr>
      <th>Game #</th>
      <th>Winner</th>
      <th>Loser</th>
      <th>Game Details</th>
    </tr>
  </thead>
  <tbody>
    {% for game in games %}
    <tr>
      <td> {{ game.game_id }} </td>
      <td> {{ game.winner }} </td>
      <td> {{ game.loser }} </td>
      <td>
        <a href="{% url 'game:game_details' game.game_id %}">
          <span style="white-space: nowrap;">Details</span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
  </div>
{% endblock %}

templates/game/gameover.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% if winner %}
            <h1> {{ winner }} has won!!!</h1>
            <h2> {{ loser }} has lost. Maybe {{ loser }} should try solitaire. </h2>
        {% else %}
            <h1> gameover, no winner</h1>
        {% endif%}
    </div>


{% endblock %}

templates/game/gameplay.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:{{ view_url }}' %}" method="post">
                    <h4>Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}

templates/game/lay_off.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:lay_off' %}" method="post">
                    <h4>Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}

templates/game/meld_options.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:meld_options' %}" method="post">
                    <h4>Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}

templates/game/melds.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:melds' %}" method="post">
                    <h4>Meld Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}

templates/game/play_meld.html
{% extends "game/base.html" %}
{% block turn_block %}
    <div class="turn_container">
        {% block gameplay_form %}
            {% if gameplay_form %}
                <form action="{% url 'game:play_meld' %}" method="post">
                    <h4>Options:</h4>
                    {% csrf_token %}
                    {% for choice in gameplay_form %}
                        {{ choice }}
                    {% endfor %}
                    <input type="submit" value="Select" />
                </form>
            {% endif %}
        {% endblock %}
    </div>

{% endblock %}